"""scope idempotency keys per user

The initial schema made ``idempotency_key`` globally unique, which meant one learner's answer
could block another learner submitting the identical answer to the same question (the natural key
is derived from question + answer, so collisions across users are expected, not exceptional).

This replaces the global uniqueness with per-user uniqueness. It only relaxes a constraint, so it
cannot fail on existing data.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-06 22:31:04.645436

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_activity_results_idempotency_key'), 'activity_results', type_='unique')
    op.create_unique_constraint('uq_activity_results_user_idempotency', 'activity_results', ['user_id', 'idempotency_key'])
    op.drop_constraint(op.f('uq_question_responses_idempotency_key'), 'question_responses', type_='unique')
    op.create_unique_constraint('uq_question_responses_user_idempotency', 'question_responses', ['user_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_question_responses_user_idempotency', 'question_responses', type_='unique')
    op.create_unique_constraint(op.f('uq_question_responses_idempotency_key'), 'question_responses', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_activity_results_user_idempotency', 'activity_results', type_='unique')
    op.create_unique_constraint(op.f('uq_activity_results_idempotency_key'), 'activity_results', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
